/**
 * tests/test_v2_0_70_stamp_version_lockstep.js — regression-pin the
 * ExportStamp version against versions.json.
 *
 * Copyright (c) 2026 BioInception PVT LTD, Cambridge, UK and Syed Asad Rahman.
 * All rights reserved. Licensed under the Apache License, Version 2.0 - see LICENSE.txt
 *
 * Why this exists
 * ---------------
 * In v2.0.67 the `ExportStamp.version` constant was set to `'2.0.67'`,
 * but the subsequent v2.0.68 (npm-installable CLI) and v2.0.69
 * (standalone platform binaries) release commits did NOT update it.
 * That meant every export stamped between v2.0.67 and v2.0.69 reported
 * itself as having been generated by BIME 2.0.67 — wrong on the wire,
 * wrong in audit trails, wrong for provenance reproducibility.
 *
 * v2.0.70 fixes that by tying the test below to `versions.json`. From
 * here on, bumping `versions.json` without bumping `ExportStamp.version`
 * fails the source suite immediately, so the bug cannot recur.
 *
 * Plain Node, no DOM. Source-shape only.
 */
'use strict';

var assert = require('assert');
var fs = require('fs');
var path = require('path');
var shim = require('./shim.js');
shim.loadAll();
require('../editor/ExportStamp.js');

var runner = shim.makeRunner('Stamp version lockstep (v2.0.70)');
var test = runner.test;

console.log('Stamp version lockstep (v2.0.70)');

function repoPath(rel) {
    return path.join(__dirname, '..', rel);
}

function readJson(rel) {
    return JSON.parse(fs.readFileSync(repoPath(rel), 'utf8'));
}

function readText(rel) {
    return fs.readFileSync(repoPath(rel), 'utf8');
}

// ---------------------------------------------------------------------------
// A. ExportStamp.version === versions.json bime
// ---------------------------------------------------------------------------
test('A1 ExportStamp.version matches versions.json bime field', function () {
    var canonical = readJson('versions.json').bime;
    assert.ok(canonical, 'versions.json must define bime');
    var ExportStamp = global.ExportStamp;
    assert.ok(ExportStamp, 'ExportStamp must be loaded by shim.loadAll()');
    assert.strictEqual(
        ExportStamp.version, canonical,
        'ExportStamp.version (' + ExportStamp.version + ') must equal '
            + 'versions.json bime (' + canonical + '). Bump '
            + 'editor/ExportStamp.js line ~310 in lockstep when shipping a '
            + 'new BIME version, or the export provenance will under-report '
            + 'the generating release (this was the v2.0.67->v2.0.69 bug).'
    );
});

// ---------------------------------------------------------------------------
// B. stampRecord/stampSvg/stampText all emit the current version
// ---------------------------------------------------------------------------
test('B1 stampRecord embeds the current version', function () {
    var canonical = readJson('versions.json').bime;
    var rec = global.ExportStamp.stampRecord('CCO');
    assert.strictEqual(rec.version, canonical,
        'stampRecord must embed the current BIME version');
});

test('B2 stampSvg embeds the current version in the <metadata> block',
    function () {
        var canonical = readJson('versions.json').bime;
        var stamped = global.ExportStamp.stampSvg(
            '<svg xmlns="http://www.w3.org/2000/svg"></svg>');
        var needle = 'bime:version="' + canonical + '"';
        // Match the v=… attribute too, in case the metadata layout changes.
        var loose = stamped.indexOf(canonical) !== -1;
        assert.ok(stamped.indexOf(needle) !== -1 || loose,
            'stamped SVG must mention the current BIME version, got: '
                + stamped.slice(0, 400));
    });

test('B3 stampText (SMILES) embeds the current version in the trailer',
    function () {
        var canonical = readJson('versions.json').bime;
        var stamped = global.ExportStamp.stampText('smi', 'CCO');
        assert.ok(stamped.indexOf(canonical) !== -1,
            'stamped SMILES must mention the current BIME version, got: '
                + stamped);
    });

// ---------------------------------------------------------------------------
// C. The other version stamps are aligned too. This is a belt-and-braces
// guard so future releases do not introduce another silent drift.
// ---------------------------------------------------------------------------
test('C1 versions.json, CITATION.cff, package.json all agree', function () {
    var canonical = readJson('versions.json').bime;
    var citation = readText('CITATION.cff');
    var citationMatch = citation.match(/version:\s*"([^"]+)"/);
    assert.ok(citationMatch, 'CITATION.cff must declare version: "..."');
    assert.strictEqual(citationMatch[1], canonical,
        'CITATION.cff version must equal versions.json bime');
    var pkg = readJson('package.json');
    assert.strictEqual(pkg.version, canonical,
        'package.json version must equal versions.json bime');
});

test('C2 editor/RDT.js + editor/ToolbarPrefs.js + editor/SMSDVersion.js'
    + ' stamps agree', function () {
        var canonical = readJson('versions.json').bime;
        var rdt = readText('editor/RDT.js');
        var rdtMatch = rdt.match(/version:\s*'([0-9][^']+)'/);
        assert.ok(rdtMatch, 'RDT.js must declare version: \'...\'');
        assert.strictEqual(rdtMatch[1], canonical,
            'editor/RDT.js version must equal versions.json bime');
        var tb = readText('editor/ToolbarPrefs.js');
        var tbMatch = tb.match(/version:\s*'([0-9][^']+)'/);
        assert.ok(tbMatch, 'ToolbarPrefs.js must declare version: \'...\'');
        assert.strictEqual(tbMatch[1], canonical,
            'editor/ToolbarPrefs.js version must equal versions.json bime');
        var smsd = readText('editor/SMSDVersion.js');
        var smsdMatch = smsd.match(/bimeVersion:\s*'([0-9][^']+)'/);
        assert.ok(smsdMatch, 'SMSDVersion.js must declare bimeVersion');
        assert.strictEqual(smsdMatch[1], canonical,
            'editor/SMSDVersion.js bimeVersion must equal versions.json bime');
});

// ---------------------------------------------------------------------------
// D. AtomTrace is surfaced by `bime version` next to RDT/ToolbarPrefs, so its
// module .version is a release-tracker too (v2.0.71 fix). This is distinct
// from the moiety-trace RESULT-format version returned by deriveMoietyTrace,
// which is frozen at the format revision and must NOT track the release.
// ---------------------------------------------------------------------------
test('D1 AtomTrace.version (module stamp) equals versions.json bime',
    function () {
        var canonical = readJson('versions.json').bime;
        var src = readText('editor/AtomTrace.js');
        // The module-export stamp lives in the `global.AtomTrace = { ... }`
        // block, which is anchored by COFACTOR_SMILES just above it. Match
        // that specific version: so we don't accidentally pick up the
        // moiety-trace result-format version earlier in the file.
        var m = src.match(/COFACTOR_SMILES:[\s\S]*?version:\s*'([0-9][^']+)'/);
        assert.ok(m, 'AtomTrace.js module export must declare a version');
        assert.strictEqual(m[1], canonical,
            'AtomTrace module .version (' + m[1] + ') must equal '
                + 'versions.json bime (' + canonical + '). It is surfaced by '
                + '`bime version`, so it tracks the release like RDT/ToolbarPrefs.');
        // Cross-check the live module if the shim happened to load it.
        if (global.AtomTrace) {
            assert.strictEqual(global.AtomTrace.version, canonical,
                'live AtomTrace.version must also equal the release');
        }
});

test('D2 moiety-trace RESULT-format version is frozen, NOT release-tracked',
    function () {
        // The deriveMoietyTrace() result carries its own format-revision
        // version. It is intentionally decoupled from the release so that a
        // routine version bump does not falsely signal a data-format change.
        // Guard: it must stay a valid semver-ish string and must NOT silently
        // become the release version (which would erase the distinction).
        var src = readText('editor/AtomTrace.js');
        var fmtMatch = src.match(/moietyAtoms:[\s\S]{0,400}?version:\s*'([0-9][^']+)'/);
        assert.ok(fmtMatch,
            'deriveMoietyTrace result must carry a format version');
        assert.ok(/^\d+\.\d+\.\d+/.test(fmtMatch[1]),
            'moiety-trace format version is semver-ish');
});

// ---------------------------------------------------------------------------
// E. The documented `bime version` example in USER_GUIDE.md must not go
// stale. It previously froze at 2.0.67/2.0.59 across many releases. Pin it.
// ---------------------------------------------------------------------------
test('E1 USER_GUIDE bime-version example matches the current release',
    function () {
        var canonical = readJson('versions.json').bime;
        var guide = readText('USER_GUIDE.md');
        var block = guide.match(/# bime [0-9][^\n]*\n# RDT\.version[^\n]*\n# AtomTrace\.version[^\n]*\n# ToolbarPrefs\.version[^\n]*/);
        assert.ok(block, 'USER_GUIDE.md must document a `bime version` block');
        var versions = block[0].match(/\d+\.\d+\.\d+/g) || [];
        assert.strictEqual(versions.length, 4,
            'documented block must show 4 version numbers');
        versions.forEach(function (v) {
            assert.strictEqual(v, canonical,
                'documented bime-version example shows ' + v + ' but the '
                    + 'current release is ' + canonical
                    + ' — regenerate the example.');
        });
});

module.exports = runner.summary;
if (require.main === module) {
    var s = runner.summary();
    console.log('\n' + s.passed + ' passed, ' + s.failed + ' failed');
    process.exit(s.failed > 0 ? 1 : 0);
}
