#!/usr/bin/env node
/**
 * tools/release-check.js - fail-closed release/CI verification.
 *
 * Runs the source suite, rebuilds the distributable bundle, verifies hashes
 * and SRI strings from the generated bytes, then fails if build-owned files
 * drift from git. No dependencies, no network.
 */
'use strict';

var fs = require('fs');
var path = require('path');
var crypto = require('crypto');
var child_process = require('child_process');

var ROOT = path.join(__dirname, '..');
var DIST = path.join(ROOT, 'dist');
var VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'versions.json'), 'utf8')).bime;

var BUILD_OWNED = [
    'dist/bime.js',
    'dist/bime.min.js',
    'dist/MANIFEST.sha256',
    'dist/SRI.txt',
    'index.html',
    'workbench.html',
    'examples.html',
    'docs.html',
    'screenshots.html',
    'test.html'
];

var PRIVATE_PATH_RE = /(^|\/)(private|internal|proprietary|local-private)(\/|$)|^tools\/private\//i;
var SECRET_PATH_RE = /(^|\/)\.env($|\.|\/)|\.(pem|p12|pfx|key)$/i;
var PRIVATE_MARKER_RE = /\b(BIME_PRIVATE|PRIVATE_ONLY|INTERNAL_ONLY|PROPRIETARY_INTERNAL)\b/;
var PRIVATE_PUBLIC_URL_RE = /(?:https?:\/\/)?(?:www\.)?(?:github\.com\/asad\/bime|asad\.github\.io\/bime)(?!-dist)(?:\.git|\/|$|[\s"'<>)])|\basad\/bime(?!-dist)\b/;
var MALFORMED_PUBLIC_URL_RE = /\bbime-dist(?:-dist)+\b/;
var PUBLIC_THIRD_PARTY_RE = new RegExp('\\b(' + [
    ['rd', 'kit'].join(''),
    ['open', 'babel'].join(''),
    ['chem', 'draw'].join(''),
    ['ket', 'cher'].join(''),
    ['os', 'ra'].join(''),
    ['rev', 'vity'].join(''),
    ['ep', 'am'].join(''),
    ['free', 'chem', 'draw'].join(''),
    ['chem', 'trade', 'hub'].join('')
].join('|') + ')\\b', 'i');
var GENERATED_AUTHOR_RE = new RegExp('\\b(' + [
    ['co-', 'authored-by'].join(''),
    ['generated by ', '(?:a', 'i|l', 'lm)'].join(''),
    ['a', 'i-generated'].join(''),
    ['l', 'lm-generated'].join(''),
    ['cla', 'ude'].join(''),
    ['anth', 'ropic'].join(''),
    ['chat', 'gpt'].join(''),
    ['open', 'ai'].join('')
].join('|') + ')\\b', 'i');

function run(label, command, args, options) {
    console.log('\n[release-check] ' + label);
    var res = child_process.spawnSync(command, args || [], {
        cwd: ROOT,
        stdio: 'inherit',
        env: Object.assign({}, process.env, (options && options.env) || {})
    });
    if (res.status !== 0) {
        throw new Error(label + ' failed with exit ' + res.status);
    }
}

function sha256Hex(file) {
    return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

function sha384Sri(file) {
    return 'sha384-' + crypto.createHash('sha384')
        .update(fs.readFileSync(file))
        .digest('base64');
}

function verifyManifest() {
    var manifestPath = path.join(DIST, 'MANIFEST.sha256');
    var manifest = fs.readFileSync(manifestPath, 'utf8');
    ['bime.js', 'bime.min.js'].forEach(function(file) {
        var expected = sha256Hex(path.join(DIST, file)) + '  ' + file;
        if (manifest.indexOf(expected) < 0) {
            throw new Error('MANIFEST.sha256 drift for ' + file);
        }
    });
    if (manifest.indexOf('BIME v' + VERSION) < 0) {
        throw new Error('MANIFEST.sha256 version drift: expected v' + VERSION);
    }
}

function verifySri() {
    var sriPath = path.join(DIST, 'SRI.txt');
    var sri = fs.readFileSync(sriPath, 'utf8');
    ['bime.js', 'bime.min.js'].forEach(function(file) {
        var expected = '<script src="' + file + '" integrity="' +
            sha384Sri(path.join(DIST, file)) + '" crossorigin="anonymous"></script>';
        if (sri.indexOf(expected) < 0) {
            throw new Error('SRI.txt drift for ' + file);
        }
    });
    if (sri.indexOf('BIME v' + VERSION) < 0) {
        throw new Error('SRI.txt version drift: expected v' + VERSION);
    }
}

function verifyBundleVersion() {
    var bundleHead = fs.readFileSync(path.join(DIST, 'bime.js'), 'utf8').slice(0, 4096);
    var minHead = fs.readFileSync(path.join(DIST, 'bime.min.js'), 'utf8').slice(0, 4096);
    var token = 'bundled BIME v' + VERSION;
    if (bundleHead.indexOf(token) < 0) throw new Error('dist/bime.js version drift');
    if (minHead.indexOf(token) < 0) throw new Error('dist/bime.min.js version drift');
}

function gitDiffBuildOwned() {
    var git = child_process.spawnSync('git', ['rev-parse', '--is-inside-work-tree'], {
        cwd: ROOT,
        encoding: 'utf8'
    });
    if (git.status !== 0 || String(git.stdout).trim() !== 'true') return;
    if (process.env.BIME_RELEASE_ALLOW_DIRTY === '1') {
        console.warn('[release-check] BIME_RELEASE_ALLOW_DIRTY=1; skipping git drift check');
        return;
    }
    var diff = child_process.spawnSync('git', ['diff', '--exit-code', '--'].concat(BUILD_OWNED), {
        cwd: ROOT,
        encoding: 'utf8'
    });
    if (diff.status !== 0) {
        process.stdout.write(diff.stdout || '');
        process.stderr.write(diff.stderr || '');
        throw new Error('build-owned files changed; run node tools/build.js and commit the results');
    }
}

function gitLsFiles() {
    var res = child_process.spawnSync('git', ['ls-files', '-z'], {
        cwd: ROOT,
        encoding: 'utf8'
    });
    if (res.status !== 0) return [];
    return String(res.stdout || '').split('\0').filter(Boolean);
}

function isPublicSurfaceFile(file) {
    if (/^(README|USER_GUIDE|CHANGES|CONTRIBUTING|SUPPORT|CITATION)\./.test(file)) return true;
    if (file === 'LICENSE.txt') return true;
    if (/^(index|workbench|examples|docs|screenshots|test|user-guide)\.html$/.test(file)) return true;
    if (/^docs\/[^/]+\.md$/.test(file)) return true;
    if (/^\.github\/(ISSUE_TEMPLATE\/.*|REPO_DESCRIPTION\.md)$/.test(file)) return true;
    if (/^dist\/(bime|bime\.min)\.js$/.test(file)) return true;
    if (/^dist\/(MANIFEST\.sha256|SRI\.txt)$/.test(file)) return true;
    return false;
}

function verifyPublicSurfaceFile(file) {
    var body = fs.readFileSync(path.join(ROOT, file), 'utf8');
    if (PRIVATE_PUBLIC_URL_RE.test(body)) {
        throw new Error('private repository or Pages URL leaked into public surface: ' + file);
    }
    if (MALFORMED_PUBLIC_URL_RE.test(body)) {
        throw new Error('malformed public release URL in public surface: ' + file);
    }
    if (PUBLIC_THIRD_PARTY_RE.test(body)) {
        throw new Error('named third-party product/tool reference in public surface: ' + file);
    }
    if (GENERATED_AUTHOR_RE.test(body)) {
        throw new Error('generated-author marker in public surface: ' + file);
    }
}

function verifyPublicReleaseBoundary() {
    var tracked = gitLsFiles();
    var blocked = tracked.filter(function(file) {
        return PRIVATE_PATH_RE.test(file) || SECRET_PATH_RE.test(file);
    });
    if (blocked.length) {
        throw new Error('private/local-only files are tracked: ' + blocked.join(', '));
    }
    tracked.filter(isPublicSurfaceFile).forEach(verifyPublicSurfaceFile);
}

function verifyPublicBundleBoundary() {
    ['bime.js', 'bime.min.js'].forEach(function(file) {
        var p = path.join(DIST, file);
        var body = fs.readFileSync(p, 'utf8');
        if (PRIVATE_MARKER_RE.test(body)) {
            throw new Error('private-only marker found in dist/' + file);
        }
    });
}

function main() {
    console.log('\n[release-check] public/private release boundary');
    verifyPublicReleaseBoundary();

    run('source regression suite', process.execPath, ['tools/run-tests.js']);
    run('layout pipeline integration verification', process.execPath, ['tools/verify-v1817.js']);
    run('bundle build + bundle suites', process.execPath, ['tools/build.js']);

    console.log('\n[release-check] manifest/SRI/version integrity');
    verifyManifest();
    verifySri();
    verifyBundleVersion();
    verifyPublicBundleBoundary();

    console.log('\n[release-check] build-owned git drift');
    gitDiffBuildOwned();

    console.log('\n[release-check] OK');
}

try {
    main();
} catch (err) {
    console.error('\nrelease-check failed: ' + (err && err.message ? err.message : err));
    process.exit(1);
}
